project:
  type: website
  output-dir: docs

website:
  #title:
  navbar:
    background: "#2C3E50"
    #foreground: success
    left:
      - href: index.qmd
        text: Home
      - href: articles.qmd
        text: Portfolio
      - href: cycling.qmd
        text: Cycling activities
  page-footer: 
    center: "Copyright &copy; 2024 Florian Ricour. All rights reserved."
    background: light
  favicon: favicon-16x16.png

format:
  html:
    theme: 
      light: cosmo
      #dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: source

execute: 
  echo: false
  warning: false
  error: true
  cache: true
